---
title: "EDA for Regression"
author: "Darya Vanichkina"
exercises: 0
keypoints: 
- Regression is the prediction of the value of a continuous variable based on one or more other continuous or categorical variables.
- Exploratory data analysis is the essential first step in ML
objectives: 
- Introduce some of the key packages for EDA and ML
- Introduce and explore the Ames Housing dataset
questions: 
- How do we predict one continuous variable based on others?
- What is the first step of any ML project (and often the most time consuming)?
source: Rmd
start: 0
teaching: 30
bibliography: references.bib
---


```{r loadLibraries}
# set knitr options
# opts_knit$set(warning = FALSE, message = FALSE)
  
library(tidyverse)
library(caret)
library(tidymodels)
library(naniar) # for visualising missing data
library(GGally) # for EDA
library(psych)
library(corrplot)
library(AmesHousing)

```



## Fitting a model

There are currently 237 types of ML models than can be fit using the caret package. To see a list of these, and to explore what tuning parameters they might need, [see here](https://topepo.github.io/caret/available-models.html). You can also [define your own model](https://topepo.github.io/caret/available-models.html).

### Simple linear regression



### Tmp
```{r}
# set.seed(1234)
# svmFit <- train(SalePriceLog ~,
#                 data = ameshousingFiltTrain,
#                 method = "svmRadial",
#                 preProc = c("center", "scale"),
#                 trControl = trainControl(method = "repeatedcv",
#                                          repeats = 10,
#                                          classProbs = TRUE)
#                 )
# predict

```





## References


  
  