---
title: "Additional resources"
author: "Darya Vanichkina"
exercises: 0
keypoints: 
- Where to go to from here.
objectives: 
- Where to go to from here.
questions: 
- Where can I learn more?
source: Rmd
start: 0
teaching: 30
---


```{r echo=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("99-")
```

## Additional resources 


## Packages used


```{r}

list_of_pkgs <- c(
"AmesHousing", 
"GGally", 
"Rtsne", 
"bestNormalize", 
"caret", 
"cluster", 
"corrplot", 
"data.table", 
"dendextend" , 
"e1071", 
"factoextra", 
"gbm", 
"ggplot2", 
"kernlab", 
"lattice", 
"mlbench", 
"naniar" , 
"pROC", 
"pheatmap" , 
"plotROC", 
"psych", 
"ranger", 
"tidymodels", 
"tidyverse", 
"xgboost", 
"vip")

# run the following line of code to install the packages you currently do not have
new_pkgs <- list_of_pkgs[!(list_of_pkgs %in% installed.packages()[,"Package"])]
if(length(new_pkgs)) install.packages(new_pkgs)
```




We will use the following packages in this course:

- caret
- ggplot2
- tidyverse
- forecast


- mlbench
- class
- caTools
- randomForst
- impute
- ranger
- kernlab
- class
- glmnet
- naivebayes
- rpart
- rpart.plot

The following materials were used in the preparation of this course:

- [UC Business Analytics R programming guide](http://uc-r.github.io)